# This script was updated/written by Alaina Pearce in Winter 2026
# to create a json file for the Rolls Collection
#
#     Copyright (C) 2026 Alaina L Pearce
#
#     This program is free software: you can redistribute it and/or modify
#     it under the terms of the GNU General Public License as published by
#     the Free Software Foundation, either version 3 of the License, or
#     (at your option) any later version.
#
#     This program is distributed in the hope that it will be useful,
#     but WITHOUT ANY WARRANTY; without even the implied warranty of
#     MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#     GNU General Public License for more details.
#
#     You should have received a copy of the GNU General Public License
#     along with this program.  If not, see <https://www.gnu.org/licenses/>.

vas_yogurt_list <- list(
  "@context" = "http://schema.org/",
  "@type" = "Dataset",
  "name" = "study-hourly_assay-vas_data.csv",
  "description" = "Self-reported state feelings during the yogurt preload lunches for the dataset titled: Route of Nutrient Delivery and Satiety in Men: Data from a 1991 IV and Intragastric Infusion Study",
  "schemaVersion" = "Psych-DS 0.1.0",
  "General" = list("MissingValueCode" = "All missing values in this dataset are represented by n/a"),
  "variableMeasured" = list(
    list("name" = "id", 
         "description" = "participant id - note, this was randomly generated in the de-identified data to break any linkage to identifiable information originally collected with the study",
         "required" = "true",
         "@type" = "PropertyValue"),
    list("name" = "session", 
         "description" = "study session/visit number",
         "@type" = "PropertyValue"),
    list("name" = "cond", 
         "description" = "preload condition",
         "valueReference" = list(
           list( "value" = "A",
                 "label" = "no preload"),
           list( "value" = "B",
                 "label" = "high carbohydrate yogurt preload"),
           list( "value" = "C",
                 "label" = "high fat yogurt preload")),
         "@type" = "PropertyValue"),
    list("name" = "yogurt_pleasant", 
         "description" = "How pleasant is the taste of this yogurt right now (Not at all pleasant -> Extremely pleasant)",
         "unitText" = "milimeters",
         "minValue" = "39",
         "maxValue" = "100",
         "@type" = "PropertyValue"),
    list("name" = "yogurt_desire_eat", 
         "description" = "How strong is your desire to eat yogurt right now? (Not at all strong -> Extremely strong)",
         "unitText" = "milimeters",
         "minValue" = "42",
         "maxValue" = "100",
         "@type" = "PropertyValue"),
    list("name" = "yogurt_subj_cal", 
         "description" = "How many calories do you think this yogurt has (Very few calories -> Very many calories)",
         "unitText" = "milimeters",
         "minValue" = "31",
         "maxValue" = "48",
         "@type" = "PropertyValue"),
    list("name" = "yogurt_creaminess", 
         "description" = "How creamy does this yogurt taste? (Not at all creamy -> Extremely creamy)",
         "unitText" = "milimeters",
         "minValue" = "39",
         "maxValue" = "100",
         "@type" = "PropertyValue"),
    list("name" = "yogurt_fruitiness", 
         "description" = "How fruity does this yogurt taste? (Not at all fruity -> Extremely fruity)",
         "unitText" = "milimeters",
         "minValue" = "58",
         "maxValue" = "100",
         "@type" = "PropertyValue"), 
    list("name" = "yogurt_fattiness", 
         "description" = "How high in fat does this yogurt taste? (Not at all high in fat -> Extremely high in fat)",
         "unitText" = "milimeters",
         "minValue" = "24",
         "maxValue" = "45",
         "@type" = "PropertyValue"),
    list("name" = "yogurt_subj_cho", 
         "description" = "How high in carbohydrate does this yogurt taste? (Not at all high in carb. -> Extremely high in carb)",
         "unitText" = "milimeters",
         "minValue" = "32",
         "maxValue" = "49",
         "@type" = "PropertyValue"),
    list("name" = "yogurt_sweetness", 
         "description" = "How sweet does this yogurt taste? (Not at all sweet -> Extremely sweet)",
         "unitText" = "milimeters",
         "minValue" = "39",
         "maxValue" = "100",
         "@type" = "PropertyValue"),
    list("name" = "yogurt_much_eat", 
         "description" = "How much do you think you could eat of this yogurt? (A very small amount -> A very large amount)?",
         "unitText" = "milimeters",
         "minValue" = "48",
         "maxValue" = "100",
         "@type" = "PropertyValue"),
    list("name" = "time", 
         "description" = "Rating time number",
         "unitText" = "milimeters",
         "minValue" = "48",
         "maxValue" = "100",
         "@type" = "PropertyValue"),
    list("name" = "hunger", 
         "description" = "How hungry do you feel right now?",
         "unitText" = "milimeters",
         "minValue" = "0",
         "maxValue" = "98",
         "@type" = "PropertyValue"),
    list("name" = "thirst", 
         "description" = "How thirsty do you feel right now?",
         "unitText" = "milimeters",
         "minValue" = "0",
         "maxValue" = "97",
         "@type" = "PropertyValue"), 
    list("name" = "fullness", 
         "description" = "How full does your stomache feel right now?",
         "unitText" = "milimeters",
         "minValue" = "1",
         "maxValue" = "100",
         "@type" = "PropertyValue"),
    list("name" = "desire_eat", 
         "description" = "How much do you want to eat right now?",
         "unitText" = "milimeters",
         "minValue" = "0",
         "maxValue" = "98",
         "@type" = "PropertyValue"),
    list("name" = "much_eat", 
         "description" = "How much do you think you could eat right now?",
         "unitText" = "milimeters",
         "minValue" = "0",
         "maxValue" = "100",
         "@type" = "PropertyValue"),
    list("name" = "nausea", 
         "description" = "How nauseated do you feel right now?",
         "unitText" = "milimeters",
         "minValue" = "0",
         "maxValue" = "84",
         "@type" = "PropertyValue")))