# This script was updated/written by Alaina Pearce in Winter 2026
# to create a json file for the Rolls Collection
#
#     Copyright (C) 2026 Alaina L Pearce
#
#     This program is free software: you can redistribute it and/or modify
#     it under the terms of the GNU General Public License as published by
#     the Free Software Foundation, either version 3 of the License, or
#     (at your option) any later version.
#
#     This program is distributed in the hope that it will be useful,
#     but WITHOUT ANY WARRANTY; without even the implied warranty of
#     MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#     GNU General Public License for more details.
#
#     You should have received a copy of the GNU General Public License
#     along with this program.  If not, see <https://www.gnu.org/licenses/>.

vas_hourly_list <- list(
  "@context" = "http://schema.org/",
  "@type" = "Dataset",
  "name" = "study-hourly_assay-vas_data.csv",
  "description" = "Self-reported state feelings for the dataset titled: Route of Nutrient Delivery and Satiety in Men: Data from a 1991 IV and Intragastric Infusion Study",
  "schemaVersion" = "Psych-DS 0.1.0",
  "General" = list("MissingValueCode" = "All missing values in this dataset are represented by n/a"),
  "variableMeasured" = list(
    list("name" = "id", 
         "description" = "participant id - note, this was randomly generated in the de-identified data to break any linkage to identifiable information originally collected with the study",
         "required" = "true",
         "@type" = "PropertyValue"),
    list("name" = "group", 
         "description" = "study group",
         "valueReference" = list(
           list( "value" = "iv",
                 "label" = "intravenous delivery of preload"),
           list( "value" = "ig",
                 "label" = "intragastric delivery of preload")),
         "@type" = "PropertyValue"),
    list("name" = "cond", 
         "description" = "preload condition",
         "valueReference" = list(
           list( "value" = "cho",
                 "label" = "iv: charbohydrate preload"),
           list( "value" = "fat",
                 "label" = "iv: fat preload"),
           list( "value" = "saline",
                 "label" = "iv: isotonic saliene preload"),
           list( "value" = "cho-long",
                 "label" = "ig: slow/long delivery charbohydrate preload"),
           list( "value" = "fat-long",
                 "label" = "ig: slow/long delivery fat preload"),
           list( "value" = "saline-long",
                 "label" = "ig: slow/long delivery isotonic saliene preload"),
           list( "value" = "cho-rapid",
                 "label" = "ig: rapid/quick delivery charbohydrate preload"),
           list( "value" = "fat-rapid",
                 "label" = "ig: rapid/quick delivery fat preload"),
           list( "value" = "saline-rapid",
                 "label" = "ig: rapid/quick delivery isotonic saliene preload")),
         "@type" = "PropertyValue"),
    list("name" = "time", 
         "description" = "reporting period",
         "valueReference" = list(
           list( "value" = "1",
                 "label" = "immediately before infusion"),
           list( "value" = "2",
                 "label" = "hour 1 post infusion"),
           list( "value" = "3",
                 "label" = "hour 2 post infusion"),
           list( "value" = "4",
                 "label" = "hour 3 post infusion"),
           list( "value" = "5",
                 "label" = "prelunch (around noon)"),
           list( "value" = "6",
                 "label" = "post lunch"),
           list( "value" = "7",
                 "label" = "hour 1 post lunch"),
           list( "value" = "8",
                 "label" = "hour 2 post lunch"),
           list( "value" = "9",
                 "label" = "hour 3 post lunch"),
           list( "value" = "10",
                 "label" = "hour 4 post lunch"),
           list( "value" = "11",
                 "label" = "hour 5 post lunch"),
           list( "value" = "12",
                 "label" = "pre dinner (around 7:30pm)"),
           list( "value" = "13",
                 "label" = "post dinner"),
           list( "value" = "14",
                 "label" = "hour 1 post dinner"),
           list( "value" = "15",
                 "label" = "hour 2 post dinner"),
           list( "value" = "16",
                 "label" = "hour 3 post dinner"),
           list( "value" = "17",
                 "label" = "hour 4 post dinner")),
         "@type" = "PropertyValue"),
    list("name" = "hunger", 
         "description" = "How hungry do you feel right now?",
         "unitText" = "milimeters",
         "minValue" = "0",
         "maxValue" = "100",
         "@type" = "PropertyValue"),
    list("name" = "fullness", 
         "description" = "How full does your stomache feel right now?",
         "unitText" = "milimeters",
         "minValue" = "0",
         "maxValue" = "100",
         "@type" = "PropertyValue"),
    list("name" = "nausea", 
         "description" = "How nauseated do you feel right now?",
         "unitText" = "milimeters",
         "minValue" = "0",
         "maxValue" = "53",
         "@type" = "PropertyValue"),
    list("name" = "thirst", 
         "description" = "How thirsty do you feel right now?",
         "unitText" = "milimeters",
         "minValue" = "0",
         "maxValue" = "97",
         "@type" = "PropertyValue"), 
    list("name" = "desire", 
         "description" = "How much do you want to eat right now?",
         "unitText" = "milimeters",
         "minValue" = "0",
         "maxValue" = "100",
         "@type" = "PropertyValue"),
    list("name" = "cramps", 
         "description" = "How much discomfort from stomach cramps do you right now?",
         "unitText" = "milimeters",
         "minValue" = "0",
         "maxValue" = "100",
         "@type" = "PropertyValue"),
    list("name" = "bloated", 
         "description" = "How bloated do you feel right now?",
         "unitText" = "milimeters",
         "minValue" = "0",
         "maxValue" = "75",
         "@type" = "PropertyValue")))