# This script was upadated/written by Alaina Pearce in Winter 2026
# to create a json file for the Rolls Collection
#
#     Copyright (C) 2026 Alaina L Pearce
#
#     This program is free software: you can redistribute it and/or modify
#     it under the terms of the GNU General Public License as published by
#     the Free Software Foundation, either version 3 of the License, or
#     (at your option) any later version.
#
#     This program is distributed in the hope that it will be useful,
#     but WITHOUT ANY WARRANTY; without even the implied warranty of
#     MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#     GNU General Public License for more details.
#
#     You should have received a copy of the GNU General Public License
#     along with this program.  If not, see <https://www.gnu.org/licenses/>.

yogurt_vas_list <- list(
  "@context" = "http://schema.org/",
  "@type" = "Dataset",
  "name" = "study-yogurt_assay-vas_data.csv",
  "description" = "Visual analog scale ratings - Yogurt Preload Study",
  "schemaVersion" = "Psych-DS 0.1.0",
  "General" = list("MissingValueCode" = "All missing values in this dataset are represented by n/a"),
  "variableMeasured" = list(
    list("name" = "id", 
         "description" = "participant id - note, this was randomly generated in the de-identified data to break any linkage to identifiable information originally collected with the study",
         "required" = "true",
         "@type" = "PropertyValue"),
    list("name" = "group", 
         "description" = "eating disorder group",
         "valueReference" = list(
           list( "value" = "0",
                 "label" = "anorexia nervosa - binge subtype"),
           list( "value" = "1",
                 "label" = "bulimia nervosa"),
           list( "value" = "2",
                 "label" = "anorexia nervosa - restrictive subtype"),
           list( "value" = "3",
                 "label" = "control - no eating disorder")),
         "@type" = "PropertyValue"),
    list("name" = "session", 
         "description" = "yogurt preload session number",
         "minValue" = "1",
         "maxValue" = "3",
         "@type" = "PropertyValue"),
  list("name" = "condition", 
       "description" = "yogurt preload condition",
       "valueReference" = list(
         list( "value" = "a",
               "label" = "high carbohydrate yogurt"),
         list( "value" = "b",
               "label" = "high fat yogurt"),
         list( "value" = "c",
               "label" = "control yogurt")),
  "@type" = "PropertyValue"),
    list("name" = "time", 
         "description" = "time point for rating",
         "valueReference" = list(
           list( "value" = "pre_yogurt",
                 "label" = "vas ratings prior to yogurt preload"),
           list( "value" = "post_yogurt",
                 "label" = "vas ratings after yogurt preloat"),
           list( "value" = "hr1",
                 "label" = "vas ratings 1 hour after yogurt preload"),
           list( "value" = "hr2",
                 "label" = "vas ratings 2 hours after yogurt preload"),
           list( "value" = "hr3",
                 "label" = "vas ratings 3 hours after yogurt preload"),
           list( "value" = "hr4",
                 "label" = "vas ratings 4 hours after yogurt preload"),
           list( "value" = "pre_dinner",
                 "label" = "vas ratings prior to dinner"),
           list( "value" = "post_dinner",
                 "label" = "vas ratings after dinner")),
         "@type" = "PropertyValue"),
    list("name" = "alert", 
         "description" = "How alert are you right now?",
         "minValue" = "0",
         "maxValue" = "100",
         "@type" = "PropertyValue"),
    list("name" = "much_eat", 
         "description" = "How much do you think you could eat right now? ",
         "minValue" = "0",
         "maxValue" = "100",
         "@type" = "PropertyValue"),
    list("name" = "binge_desire", 
         "description" = "How strong is your wish to binge right now?",
         "minValue" = "0",
         "maxValue" = "100",
         "@type" = "PropertyValue"),
    list("name" = "bloated", 
         "description" = "How bloated do you feel right now?",
         "minValue" = "0",
         "maxValue" = "100",
         "@type" = "PropertyValue"),
    list("name" = "content", 
         "description" = "How content do you feel right now?",
         "minValue" = "0",
         "maxValue" = "100",
         "@type" = "PropertyValue"),
    list("name" = "depressed", 
         "description" = "How depressed do you feel right now?",
         "minValue" = "0",
         "maxValue" = "100",
         "@type" = "PropertyValue"),
    list("name" = "desire_eat", 
         "description" = "How much do you desire to eat right now?",
         "minValue" = "0",
         "maxValue" = "100",
         "@type" = "PropertyValue"),
    list("name" = "fear_fat", 
         "description" = "How fearful are you of becoming fat right now?",
         "minValue" = "0",
         "maxValue" = "100",
         "@type" = "PropertyValue"),
    list("name" = "fullness", 
         "description" = "How full do you feel right now?",
         "minValue" = "0",
         "maxValue" = "100",
         "@type" = "PropertyValue"),
  list("name" = "guilt", 
       "description" = "How guilty do you feel right now?",
       "minValue" = "0",
       "maxValue" = "100",
       "@type" = "PropertyValue"),
  list("name" = "hunger", 
       "description" = "How hungry do you feel right now?",
       "minValue" = "0",
       "maxValue" = "100",
       "@type" = "PropertyValue"),
  list("name" = "nausea", 
       "description" = "How nauseous do you feel right now?",
       "minValue" = "0",
       "maxValue" = "100",
       "@type" = "PropertyValue"),
  list("name" = "purge_desire", 
       "description" = "How strong is your desire to purge right now?",
       "minValue" = "0",
       "maxValue" = "100",
       "@type" = "PropertyValue"),
  list("name" = "thirst", 
       "description" = "How thirsty do you feel right now?",
       "minValue" = "0",
       "maxValue" = "100",
       "@type" = "PropertyValue")))